volumes:
  local_postgres_data: { }
  local_postgres_data_backups: { }

services:
  trainer_nginx:
    image: nginx
    container_name: trainer_nginx
    build:
      context: .
      dockerfile: ./compose/local/nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /app/backend/local-backend-static:/app/backend/local-backend-static
    depends_on:
      - trainer_backend
      - trainer_frontend
      - trainer_db
    networks:
      - backend

  trainer_db:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    container_name: trainer_db
    restart: always
    networks:
      - backend
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
      - ./local_backups:/local_backups
    env_file:
      - .envs/.local/.postgres

  trainer_frontend:
    image: vite-docker-container
    stdin_open: true
    container_name: trainer_frontend
    build:
      context: .
      dockerfile: ./compose/local/trainer_frontend/Dockerfile
    depends_on:
      - trainer_db
    networks:
      - backend
    volumes:
      - ./trainer_page:/usr/src/frontend
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  trainer_backend:
    container_name: trainer_backend
    build:
      context: .
      dockerfile: ./compose/local/trainer_backend/Dockerfile
    env_file:
      - .env.development
#    volumes:
#      - .:/code
    networks:
      - backend
    ports:
      - 8000:8000

networks:
  backend: