services:
  production_trainer_db:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    container_name: production_trainer_db
    restart: always
    networks:
      - production_backend
    env_file:
      - .envs/.production/.postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
      - ./prod_backups:/prod_backups

  production_trainer_backend:
    container_name: production_trainer_backend
    env_file:
      - .env.production
    build:
      context: .
      dockerfile: ./compose/production/trainer_backend/Dockerfile
    volumes:
      - .:/code
    networks:
      - production_backend

networks:
  production_backend:
  connector:
    external: true

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
